#shell
shell /usr/bin/fish
# -------------------------------------------------- #

# Font
# -------------------------------------------------- #
font_family      Maple Mono
# font_family      PingFang SC
font_size        12

# -------------------------------------------------- #
# Theme - Aizen Dark
# -------------------------------------------------- #
foreground            #d0d6f0
background            #1a1a1a
selection_foreground  #d0d6f0
selection_background  #333333

cursor                #f08898
cursor_text_color     #1a1a1a

url_color             #84b4f8

# black
color0  #1a1a1a
color8  #444444
# red
color1  #f08898
color9  #f08898
# green
color2  #a4e09c
color10 #a4e09c
# yellow
color3  #f5dea4
color11 #f5dea4
# blue
color4  #84b4f8
color12 #84b4f8
# magenta
color5  #c8a2f4
color13 #c8a2f4
# cyan
color6  #90dcd0
color14 #90dcd0
# white
color7  #d0d6f0
color15 #ffffff

# -------------------------------------------------- #
# Window
# -------------------------------------------------- #
window_padding_width        5
hide_window_decorations     yes
initial_window_width        150c
initial_window_height       40c
background_opacity          0.3

# -------------------------------------------------- #
# Cursor Displacement Effect
# -------------------------------------------------- #
cursor_shape              block
cursor_beam_thickness     4.0
cursor_trail              6

# -------------------------------------------------- #
# Mouse
# -------------------------------------------------- #
mouse_hide_wait           0.5

# -------------------------------------------------- #
# Tab
# -------------------------------------------------- #
new_tab_position          adjacent

# -------------------------------------------------- #
# Clipboard
# -------------------------------------------------- #
clipboard_control write-clipboard write-primary
