    hl.on("hyprland.start", function () 
        hl.exec_cmd("waybar")
end)
    hl.on("hyprland.start", function () 
        hl.exec_cmd("echo 'Xft.dpi: 192' | xrdb -merge")
end)
    hl.on("hyprland.start", function () 
        hl.exec_cmd("awww-daemon")
end)
--     hl.on("hyprland.start", function () 
--         hl.exec_cmd("mako")
-- end) 
    hl.on("hyprland.start", function ()
        hl.exec_cmd("fcitx5")
end)
    hl.on("hyprland.start", function ()
        hl.exec_cmd("/usr/lib/hyprpolkitagent/hyprpolkitagent")
end)
     hl.on("hyprland.start", function ()
        hl.exec_cmd("blueman-applet")
end)  
     hl.on("hyprland.start", function ()
        hl.exec_cmd("hypridle")
end) 
     hl.on("hyprland.start", function ()
        hl.exec_cmd("wl-paste --type text --watch cliphist store")
end)   
 hl.on("hyprland.start", function ()
        hl.exec_cmd("wl-paste --type image --watch cliphist store")
end) 
    hl.on("hyprland.start", function ()
        hl.exec_cmd("nm-applet")
end)
hl.on("hyprland.start", function ()
        hl.exec_cmd("swaync-client")
end)

